apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps
    protocol: TCP
    targetPort: 21
  - port: 10100
    name: passive-port
    protocol: TCP
    targetPort: 10100 
  type: LoadBalancer
  loadBalancerIP: 192.168.99.150